# Generated by Django 3.2.6 on 2021-09-09 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0010_simulator_pay_type'),
        ('user_profile', '0002_user_id_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Начало авторизации'), (1, 'Ошибка авторизации'), (2, 'Отказ от авторизации'), (3, 'Успех авторизации')], default=0)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('simulator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulators.simulator')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
